import { MoodOption, MoodType } from '@/types';

export const MOOD_OPTIONS: Record<MoodType, MoodOption> = {
  happy: {
    id: 'happy',
    label: 'Happy',
    emoji: '😊',
    color: '#FBBF24',
    bgLight: 'bg-amber-100/70 border-amber-300/60 text-amber-900',
    bgDark: 'dark:bg-amber-500/15 dark:border-amber-500/30 dark:text-amber-200',
    textColor: 'text-amber-600 dark:text-amber-400',
    description: 'Feeling joyful, cheerful, and full of light',
    score: 9,
  },
  excited: {
    id: 'excited',
    label: 'Excited',
    emoji: '😁',
    color: '#F59E0B',
    bgLight: 'bg-yellow-100/70 border-yellow-300/60 text-yellow-900',
    bgDark: 'dark:bg-yellow-500/15 dark:border-yellow-500/30 dark:text-yellow-200',
    textColor: 'text-yellow-600 dark:text-yellow-400',
    description: 'Eager, enthusiastic, and energized',
    score: 10,
  },
  calm: {
    id: 'calm',
    label: 'Calm',
    emoji: '😌',
    color: '#34D399',
    bgLight: 'bg-emerald-100/70 border-emerald-300/60 text-emerald-900',
    bgDark: 'dark:bg-emerald-500/15 dark:border-emerald-500/30 dark:text-emerald-200',
    textColor: 'text-emerald-600 dark:text-emerald-400',
    description: 'Peaceful, relaxed, and anchored',
    score: 8,
  },
  neutral: {
    id: 'neutral',
    label: 'Neutral',
    emoji: '😐',
    color: '#94A3B8',
    bgLight: 'bg-slate-100/70 border-slate-300/60 text-slate-900',
    bgDark: 'dark:bg-slate-500/15 dark:border-slate-500/30 dark:text-slate-200',
    textColor: 'text-slate-600 dark:text-slate-400',
    description: 'Steady, balanced, feeling okay',
    score: 5,
  },
  sad: {
    id: 'sad',
    label: 'Sad',
    emoji: '😔',
    color: '#60A5FA',
    bgLight: 'bg-blue-100/70 border-blue-300/60 text-blue-900',
    bgDark: 'dark:bg-blue-500/15 dark:border-blue-500/30 dark:text-blue-200',
    textColor: 'text-blue-600 dark:text-blue-400',
    description: 'A bit down, quiet, or reflective',
    score: 3,
  },
  depressed: {
    id: 'depressed',
    label: 'Depressed',
    emoji: '😭',
    color: '#818CF8',
    bgLight: 'bg-indigo-100/70 border-indigo-300/60 text-indigo-900',
    bgDark: 'dark:bg-indigo-500/15 dark:border-indigo-500/30 dark:text-indigo-200',
    textColor: 'text-indigo-600 dark:text-indigo-400',
    description: 'Heavy heart, exhausted, needing gentle care',
    score: 1,
  },
  angry: {
    id: 'angry',
    label: 'Angry',
    emoji: '😤',
    color: '#F87171',
    bgLight: 'bg-red-100/70 border-red-300/60 text-red-900',
    bgDark: 'dark:bg-red-500/15 dark:border-red-500/30 dark:text-red-200',
    textColor: 'text-red-600 dark:text-red-400',
    description: 'Frustrated, agitated, or tense',
    score: 2,
  },
  anxious: {
    id: 'anxious',
    label: 'Anxious',
    emoji: '😰',
    color: '#A78BFA',
    bgLight: 'bg-purple-100/70 border-purple-300/60 text-purple-900',
    bgDark: 'dark:bg-purple-500/15 dark:border-purple-500/30 dark:text-purple-200',
    textColor: 'text-purple-600 dark:text-purple-400',
    description: 'Uneasy, overthinking, or worried',
    score: 3,
  },
  stressed: {
    id: 'stressed',
    label: 'Stressed',
    emoji: '😫',
    color: '#FB923C',
    bgLight: 'bg-orange-100/70 border-orange-300/60 text-orange-900',
    bgDark: 'dark:bg-orange-500/15 dark:border-orange-500/30 dark:text-orange-200',
    textColor: 'text-orange-600 dark:text-orange-400',
    description: 'Overwhelmed by demands or pressure',
    score: 2,
  },
};

export const MOOD_LIST: MoodOption[] = Object.values(MOOD_OPTIONS);
